// src/pages/Reports.jsx
import { useState, useEffect } from "react";
import Sidebar from "../components/Sidebar";
import Navbar  from "../components/Navbar";
import MobileNav from "../components/MobileNav";
import { useNavigate } from "react-router-dom";
import { getUserCases } from "../auth";
import { SkeletonTable } from "../components/Skeleton";
import { useToast } from "../components/Toast";
import jsPDF from "jspdf";

function Reports() {
  const navigate      = useNavigate();
  const toast         = useToast();
  const [cases, setCases]     = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getUserCases().then(c => { setCases(c || []); setLoading(false); });
  }, []);

  const handleDownload = (c) => {
    const doc  = new jsPDF();
    const risk = c.risk || c.result?.risk || "—";
    const r    = c.result || c;

    // Header
    doc.setFillColor(10, 61, 98);
    doc.rect(0, 0, 210, 40, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("EndoAI", 14, 18);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("AI-Based Volumetric Canal Planning Report", 14, 27);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 34);

    // Case Info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Case Information", 14, 52);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const info = [
      ["Case ID",      c.case_id || c.caseId],
      ["Patient ID",   c.patient_id || c.patientId],
      ["Tooth Number", `#${c.tooth}`],
      ["Date",         c.upload_date || c.uploadDate],
      ["Risk Level",   risk],
    ];
    info.forEach(([k, v], i) => {
      doc.setFont("helvetica", "bold");
      doc.text(`${k}:`, 14, 62 + i * 8);
      doc.setFont("helvetica", "normal");
      doc.text(String(v || "—"), 60, 62 + i * 8);
    });

    // Measurements
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Volumetric Measurements", 14, 112);
    doc.setFontSize(10);
    const measurements = [
      ["Canal Volume",     `${r.canal_volume ?? "—"} mm³`],
      ["Canal Length",     `${r.canal_length ?? "—"} mm`],
      ["Curvature",        `${r.curvature ?? "—"}°`],
      ["Dentin Thickness", `${r.dentin ?? "—"} mm`],
      ["No. of Canals",    String(r.n_canals ?? "—")],
    ];
    measurements.forEach(([k, v], i) => {
      doc.setFont("helvetica", "bold");
      doc.text(`${k}:`, 14, 122 + i * 8);
      doc.setFont("helvetica", "normal");
      doc.text(v, 70, 122 + i * 8);
    });

    // Risk Assessment
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Risk Assessment", 14, 172);
    doc.setFontSize(10);
    const risks = [
      ["Canal Calcification",   `${r.calcification ?? "—"}%`],
      ["Ledge Formation Risk",  `${r.ledge_risk ?? "—"}%`],
      ["Perforation Risk",      `${r.perf_risk ?? "—"}%`],
      ["Instrument Separation", `${r.sep_risk ?? "—"}%`],
    ];
    risks.forEach(([k, v], i) => {
      doc.setFont("helvetica", "bold");
      doc.text(`${k}:`, 14, 182 + i * 8);
      doc.setFont("helvetica", "normal");
      doc.text(v, 80, 182 + i * 8);
    });

    // Treatment Recommendation
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Treatment Recommendation", 14, 222);
    doc.setFontSize(10);
    const recos = [
      ["Suggested Taper", r.taper   ?? "—"],
      ["Apical Size",     r.apical  ?? "—"],
      ["Irrigation",      r.irrigation ?? "—"],
      ["Obturation",      r.obturation ?? "—"],
    ];
    recos.forEach(([k, v], i) => {
      doc.setFont("helvetica", "bold");
      doc.text(`${k}:`, 14, 232 + i * 8);
      doc.setFont("helvetica", "normal");
      doc.text(v, 70, 232 + i * 8);
    });

    // Footer
    doc.setFillColor(244, 247, 251);
    doc.rect(0, 272, 210, 25, "F");
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(8);
    doc.text("This report is generated by EndoAI and is intended for clinical reference only.", 14, 280);
    doc.text("© 2026 EndoAI · HIPAA Compliant · Secure Access", 14, 286);

    doc.save(`EndoAI_Report_${c.case_id || c.caseId}.pdf`);
    toast("PDF report downloaded!", "success");
  };

  return (
    <div className="app-layout">
      <Sidebar />
      <div className="main-content">
        <Navbar />
        <div className="content-container">

          <div style={{ marginBottom: "20px" }}>
            <h1 style={{ fontSize: "20px", fontWeight: "700", marginBottom: "2px" }}>Clinical Reports</h1>
            <p style={{ color: "var(--text-muted)", fontSize: "13px" }}>
              Download and manage structured PDF reports for all clinical cases.
            </p>
          </div>

          {/* Stats */}
          <div className="stats-grid-4" style={{ marginBottom: "20px" }}>
            {[
              { label: "Total Reports", value: cases.length, color: "var(--info)", bg: "var(--info-bg)" },
              { label: "High Risk",     value: cases.filter(c => (c.risk || c.result?.risk) === "High").length, color: "var(--danger)", bg: "var(--danger-bg)" },
              { label: "Moderate Risk", value: cases.filter(c => (c.risk || c.result?.risk) === "Moderate").length, color: "var(--warning)", bg: "var(--warning-bg)" },
              { label: "Low Risk",      value: cases.filter(c => (c.risk || c.result?.risk) === "Low").length,  color: "var(--success)", bg: "var(--success-bg)" },
            ].map(s => (
              <div key={s.label} className="card" style={{ padding: "16px 20px", display: "flex", alignItems: "center", gap: "12px" }}>
                <div style={{ width: "40px", height: "40px", borderRadius: "10px", background: s.bg, display: "flex", alignItems: "center", justifyContent: "center", fontSize: "18px", fontWeight: "700", color: s.color }}>
                  {s.value}
                </div>
                <div style={{ fontSize: "13px", color: "var(--text-muted)", fontWeight: "500" }}>{s.label}</div>
              </div>
            ))}
          </div>

          {/* Reports List */}
          <div className="card">
            <div style={{ fontSize: "11px", fontWeight: "700", color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.6px", marginBottom: "16px" }}>
              All Generated Reports
            </div>

            {loading ? <SkeletonTable rows={4} /> : cases.length === 0 ? (
              <div style={{ textAlign: "center", padding: "40px 16px", color: "var(--text-muted)" }}>
                <svg width="40" height="40" fill="none" viewBox="0 0 24 24" stroke="var(--border-strong)" strokeWidth="1.3" style={{ display: "block", margin: "0 auto 12px" }}>
                  <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/><path d="M14 2v6h6M16 13H8M16 17H8"/>
                </svg>
                <p style={{ fontWeight: "600", marginBottom: "4px" }}>No reports generated yet</p>
                <p style={{ fontSize: "13px", marginBottom: "16px" }}>Analyze a CBCT scan to generate your first report.</p>
                <button onClick={() => navigate("/upload")} className="btn btn-primary" style={{ fontSize: "13px", padding: "8px 18px" }}>
                  Upload First Case
                </button>
              </div>
            ) : cases.map((c, i) => {
              const risk   = c.risk || c.result?.risk;
              const caseId = c.case_id || c.caseId;
              const patId  = c.patient_id || c.patientId;
              const date   = c.upload_date || c.uploadDate;
              return (
                <div key={caseId || i} style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "12px 0", borderBottom: i < cases.length - 1 ? "1px solid var(--border)" : "none", flexWrap: "wrap", gap: "10px" }}>
                  <div>
                    <div style={{ fontFamily: "var(--font-mono)", fontSize: "12.5px", fontWeight: "600", color: "var(--primary-light)", background: "var(--info-bg)", padding: "2px 8px", borderRadius: "4px", display: "inline-block", marginBottom: "3px" }}>
                      {caseId}
                    </div>
                    <div style={{ fontSize: "12.5px", color: "var(--text-muted)" }}>
                      Patient {patId} · Tooth #{c.tooth} · {date} ·{" "}
                      <span style={{ fontWeight: "600", color: risk === "High" ? "var(--danger)" : risk === "Low" ? "var(--success)" : "var(--warning)" }}>
                        {risk} Risk
                      </span>
                    </div>
                  </div>
                  <div style={{ display: "flex", gap: "8px" }}>
                    <button onClick={() => { localStorage.setItem("endoai_last_result", JSON.stringify(c)); navigate("/results"); }}
                      className="btn"
                      style={{ padding: "6px 12px", background: "var(--surface)", color: "var(--primary)", border: "1.5px solid var(--border)", fontSize: "12px" }}>
                      View
                    </button>
                    <button onClick={() => handleDownload(c)}
                      className="btn btn-primary"
                      style={{ padding: "6px 12px", fontSize: "12px" }}>
                      <svg width="13" height="13" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M7 10l5 5 5-5M12 15V3"/></svg>
                      PDF
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
      <MobileNav />
    </div>
  );
}

export default Reports;
